### ISSUE TITLE
Inject.rawHead and Inject.rawBody currently don't support a function as data argument

### ISSUE THREAD

**Issue by Sanjo** [meteorhacks/meteor-inject-initial#6]
Inject.rawHead and Inject.rawBody currently don't support a function as data argument. In the README it is stated `textOrFunc`, so I thought it supports a function. I used `Inject.rawModHtml` instead.

And thanks for the package. It is really helpful and easy to use.

**Comment by gadicc** [comment]
Fixed in arunoda's refactor in https://github.com/meteorhacks/meteor-inject-initial/commit/a559816a4696002adb0c043b55f3cccaf2880046 from 2014-07-23 :)  Thanks!
